### PR TITLE
Allow special chars in test suite name and title

### PR DESCRIPTION
**Pull request by mfurtado-mdsol**
**What is this PR for?**

- Fix issue https://github.com/lukejpreston/xunit-viewer/issues/5

@lukejpreston

### CODE REVIEW

**Comment by mfurtado-mdsol** [comment]
@lukejpreston can you please review/merge this PR please?

**Comment by lukejpreston** [comment]
Looks pretty good to me. Could you add a new test case for the parser. I think it is still tested. Just add an xml file and update assertion data. I’m on holiday so will take a closer look Monday morning.

**Comment by mfurtado-mdsol** [comment]
Cool, I'll do that. Thanks for responding while away.

**Comment by mfurtado-mdsol** [comment]
I have added a test to check special chars. Original test never passed as the `uuid` generated will be always different.

**Comment by lukejpreston** [comment]
That’s fine it is more of a check that nothing has broke. Haven’t invested enough time in these tests. Will merge and publish on Monday when I am back in the office.

**Comment by mfurtado-mdsol** [comment]
Hey @lukejpreston, did you got chance to take a look at this?

**Comment by lukejpreston** [comment]
sorry! thanks for reminding me. on it now

**Comment by KoenDG** [comment]
Greetings, I'm making a comment here because this still seems to be the case with version 6.1.4

I've got title with colons in them and these are getting removed.

Do I make a new ticket or commenting here enough?

**Comment by lukejpreston** [comment]
Create a new issue pleasr

**Pull request merged**
