### PR TITLE
Fix Unicode not displaying in titles

### PR DESCRIPTION
**Pull request by zeburek**
Case:

When you have any russian or another non-ASCII language symbols in Tests and Suites names - they are cutted-off in newer version of change-case

https://github.com/blakeembrey/change-case/issues/74 - here is a bug about it

### CODE REVIEW

**Comment by lukejpreston** [comment]
can you share some sample XML please? does not need to be part of the PR

**Comment by zeburek** [comment]
@lukejpreston 
Something like this:
```xml
<testsuite errors="0" failures="0" hostname="msk1wst056" name="sessions.sessions_api.Доступность эндпоинта получения списка сессий" skipped="0" tests="1" time="1.047092" timestamp="2020-02-13T12:02:50.675248">
    <testcase classname="sessions.sessions_api.Доступность эндпоинта получения списка сессий" name="Проверка доступности эндпоинта получения сессий" status="passed" time="1.047092"><system-out>
    <![CDATA[
@scenario.begin
  Сценарий: Проверка доступности эндпоинта получения сессий
    Когда Создана сессия для пользователя с аутентификацией во всех системах ... passed in 0.899s
    И Пользователь входит в мобильное приложение Aurora-market ... passed in 0.129s
    И Отправляется запрос для получения сессий для учетной записи Пользователь ... passed in 0.018s
    Тогда Возвращается количество sessions равное 1 ... passed in 0.000s
    И Возвращается количество tokens равное 1 ... passed in 0.000s

@scenario.end
--------------------------------------------------------------------------------
    ]]>
    </system-out></testcase>
</testsuite>
```

**Comment by zeburek** [comment]
@lukejpreston should I do something else for you to merge this?

**Comment by lukejpreston** [comment]
Thanks for this, a couple of things to change before I merge (I will probably update the README with this info after this PR)

1. Don't commit any file in `src/cli/static` as part of the PR, these are auto-generated
2. add a file in the `data` folder named `unicode_example.xml` and add your example you shared with me

After doing these run `npm test` should break, if it doesn't run `CI=true npm test` and that will break the `get-suites.test.js` which you will need to update.

To do this in the test I tend to add the line `console.log(JSON.stringify(suites, null, 2)` then replace the `expected` value with this new value and the tests should be running fine, you may also need to change some of the other tests as you are adding a new file. This seems more complex than it really is ;)

run `npm lint` and if that fails you can either fix everything by hand or run `npx eslint xunit-viewer.js src --ignore-pattern src/cli/static/js/**/* --fix` and that should fix most, if not all, issues

Let me know if you need any help with these steps but it shouldn't take to long to do

**Comment by lukejpreston** [comment]
Thanks for finding this

I did this for you, try 6.0.16 and let me know whether there is still something wrong

**Comment by zeburek** [comment]
Ok, thanks!

**Pull request closed without merging**
