### PR TITLE
Partially implement --filter flag logic

### PR DESCRIPTION
**Pull request by samdfonseca**
These changes partially implement the logic for the `--filter` flag described in the README, specifically the `--filter.suites.value, --filter.suites.types, --filter.tests.value, --filter-tests.types` flags. In addition, the logic for marking a suite status as `pass` is slightly changed, to consider suites that have some passing tests and the rest of the tests are skipped as passed. For example, before these changes a suite that had 1 passing test and 1 skipped test had status set to `fail`, while after these changes that suite will have status set to `pass`, since all the tests that were run passed.

### CODE REVIEW

**Comment by lukejpreston** [comment]
@samdfonseca that's awesome, I will run it locally and if I am happy I will merge it and deploy

**Comment by lukejpreston** [comment]
in the `package.json` there is this script

`"xunit-viewer:terminal": "./bin/xunit-viewer --results=data  --ignore=invalid.xml,blank_file.xml --terminal --filter.suites.search=\"bacon\" --filter.suites.hidden=pass,fail --filter.tests.search=\"bacon\" --filter.tests.hidden=error,skip --filter.properties.search=\"x\" --filter.properties.hidden=all "`

could you update it in order to make sure your code works, I am not 100% it works as I expected

Also, you want to merge master and there has been a load of vulnerability updates with nodemon

**Comment by samdfonseca** [comment]
Hey @lukejpreston thanks for considering this! These changes don't touch `--filter.suites.search, --filter.suites.hidden, --filter.tests.search, --filter.tests.hidden, --filter.properties.search, --filter.properties.hidden`, so I don't think this would affect the `xunit-viewer:terminal` script at all. Can you be more specific with what you think might be broken?

**Comment by lukejpreston** [comment]
Sorry I wasn't clear. I meant update package.json with a script which tests your code so then I won't forget to test the code should I do changes to it? As in add a new script.

**Comment by samdfonseca** [comment]
Gotcha. Ok, I've added the `xunit-viewer:filters` script. Also, while putting together that script, I noticed that `--filter.suites.value="^suite name$"` and `--filter.tests.value="^test name$"` weren't matching because the suite and test names were being title-cased. I've gone ahead and removed the title-casing, since that might cause confusion when using those filters. Let me know if that's ok or if you'd like to add that back.

**Comment by lukejpreston** [comment]
The idea is to make the tests more readable using the title casing

I would prefer you change your filter to test against lower/uppercase e.g. `items.filter(item => filter.toLowerCase().includes(item.status.toLowerCase()))`

I think once you have done that I will be happy to merge this

**Comment by lukejpreston** [comment]
The filer logic has changed and I am creating an issue to make it work with React Router and CLI

**Pull request closed without merging**
