### PR TITLE
Add support for PyTest testcase properties

### PR DESCRIPTION
**Pull request by zeburek**
Related to this specs: https://docs.pytest.org/en/latest/usage.html#record-property

It is not the original JUnit XML style, but it is possible

### CODE REVIEW

**Comment by lukejpreston** [comment]
tests can have properties! I will download this and have a look locally but it is looking good so far!

**Comment by lukejpreston** [comment]
@zeburek I will merge this, it looks great!

I think there needs to be some additional functionality which I want to raise as separate issues

* toggle properties under tests, both expand and visible
* when searching tests it will also look at test properties
* think about searching, perhaps similar to gmail filtering with something like `:name(term) :message(term) :properties(term)`

**Comment by lukejpreston** [comment]
this should be in `v6.1.3`

**Comment by zeburek** [comment]
Yeah, great!

пт, 21 февр. 2020 г., 11:03 Luke Preston <notifications@github.com>:

**Pull request merged**
